import { useState } from "react";
import { ChevronDown, ChevronRight, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { type TaxonomyKind, type TaxonomyWrite, useTaxonomyWrite } from "~/lib/mutations";
import { useTaxonomyTree } from "~/lib/queries";
import { NodeForm, type NodeValues } from "./node-form";

/** Which form is open, if any. For a create, `id` is the parent's id. */
type OpenForm = {
  kind: TaxonomyKind;
  action: "create" | "update";
  id: string;
  defaults: { nameEn: string; nameBn: string; position: number };
};

const key = (kind: TaxonomyKind, action: string, id: string) => `${kind}:${action}:${id}`;

const POSITION_LABEL: Record<TaxonomyKind, string> = {
  level: "Order",
  subject: "Order",
  book: "Order",
  chapter: "Chapter number",
};

/**
 * Builds the write for the open form. Create needs the parent id the form
 * was opened from; update needs only the row's own id.
 */
function writeFor(form: OpenForm, values: NodeValues): TaxonomyWrite {
  const names = { nameEn: values.nameEn, nameBn: values.nameBn };

  if (form.action === "create") {
    switch (form.kind) {
      case "level":
        return { kind: "level", action: "create", body: { ...names, sort: values.position } };
      case "subject":
        return {
          kind: "subject",
          action: "create",
          body: { ...names, levelId: form.id, sort: values.position },
        };
      case "book":
        return {
          kind: "book",
          action: "create",
          body: { ...names, subjectId: form.id, sort: values.position },
        };
      case "chapter":
        return {
          kind: "chapter",
          action: "create",
          body: { ...names, bookId: form.id, number: values.position },
        };
    }
  }

  switch (form.kind) {
    case "level":
      return { kind: "level", action: "update", id: form.id, body: { ...names, sort: values.position } };
    case "subject":
      return { kind: "subject", action: "update", id: form.id, body: { ...names, sort: values.position } };
    case "book":
      return { kind: "book", action: "update", id: form.id, body: { ...names, sort: values.position } };
    case "chapter":
      return { kind: "chapter", action: "update", id: form.id, body: { ...names, number: values.position } };
  }
}

/**
 * The whole syllabus, editable: class > subject > book > chapter, each row
 * with add, edit and delete. Ids are generated by the API from the English
 * name, so they are shown but never typed.
 *
 * A delete the API refuses — a class with batches on it, or anything a
 * question is already filed under — comes back as its own message.
 */
export function TaxonomyTree() {
  const levels = useTaxonomyTree();
  const write = useTaxonomyWrite();
  const [form, setForm] = useState<OpenForm | null>(null);
  const [confirming, setConfirming] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<ReadonlySet<string>>(new Set());

  const toggle = (id: string) =>
    setExpanded((open) => {
      const next = new Set(open);
      if (!next.delete(id)) next.add(id);
      return next;
    });

  const save = async (values: NodeValues) => {
    if (!form) return;
    try {
      await write.trigger(writeFor(form, values));
      toast(`${values.nameEn} saved.`);
      setForm(null);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Couldn't save that");
    }
  };

  const remove = async (kind: TaxonomyKind, id: string, name: string) => {
    setConfirming(null);
    try {
      await write.trigger({ kind, action: "delete", id });
      toast(`${name} deleted.`);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Couldn't delete that");
    }
  };

  const isOpen = (kind: TaxonomyKind, action: "create" | "update", id: string) =>
    form?.kind === kind && form.action === action && form.id === id;

  /** The add or edit form, when it belongs to this row. */
  const formFor = (kind: TaxonomyKind, action: "create" | "update", id: string) =>
    isOpen(kind, action, id) && form ? (
      <NodeForm
        key={key(kind, action, id)}
        legend={`${action === "create" ? "Add" : "Edit"} ${kind}`}
        positionLabel={POSITION_LABEL[kind]}
        minPosition={kind === "chapter" ? 1 : 0}
        defaults={form.defaults}
        busy={write.isMutating}
        onSave={save}
        onCancel={() => setForm(null)}
      />
    ) : null;

  const rowActions = (
    kind: TaxonomyKind,
    id: string,
    name: string,
    edit: OpenForm["defaults"],
    add?: { kind: TaxonomyKind; nextPosition: number },
  ) => (
    <span className="acts">
      {add && (
        <button
          type="button"
          className="btn btn-ghost btn-sm"
          aria-expanded={isOpen(add.kind, "create", id)}
          onClick={() =>
            setForm(
              isOpen(add.kind, "create", id)
                ? null
                : {
                    kind: add.kind,
                    action: "create",
                    id,
                    defaults: { nameEn: "", nameBn: "", position: add.nextPosition },
                  },
            )
          }
        >
          <Plus size={14} />
          {add.kind}
        </button>
      )}
      <button
        type="button"
        className="btn btn-ghost btn-sm"
        aria-expanded={isOpen(kind, "update", id)}
        onClick={() =>
          setForm(
            isOpen(kind, "update", id)
              ? null
              : { kind, action: "update", id, defaults: edit },
          )
        }
      >
        <Pencil size={14} />
        Edit
      </button>
      <button
        type="button"
        className="btn btn-danger btn-sm"
        aria-expanded={confirming === key(kind, "delete", id)}
        onClick={() =>
          setConfirming(
            confirming === key(kind, "delete", id) ? null : key(kind, "delete", id),
          )
        }
      >
        <Trash2 size={14} />
        Delete
      </button>
      {confirming === key(kind, "delete", id) && (
        <span className="confirm" role="alertdialog" aria-label={`Delete ${name}?`}>
          <span style={{ flex: 1, minWidth: 160 }}>Delete {name}?</span>
          <button
            type="button"
            className="btn btn-danger btn-sm"
            disabled={write.isMutating}
            onClick={() => remove(kind, id, name)}
          >
            Confirm
          </button>
          <button
            type="button"
            className="btn btn-ghost btn-sm"
            onClick={() => setConfirming(null)}
          >
            Cancel
          </button>
        </span>
      )}
    </span>
  );

  return (
    <div style={{ display: "grid", gap: 20 }}>
      <div className="toolbar">
        <span className="muted" style={{ fontSize: 14 }}>
          {levels.length} classes
        </span>
        <button
          type="button"
          className="btn btn-primary"
          aria-expanded={isOpen("level", "create", "")}
          onClick={() =>
            setForm(
              isOpen("level", "create", "")
                ? null
                : {
                    kind: "level",
                    action: "create",
                    id: "",
                    defaults: { nameEn: "", nameBn: "", position: levels.length },
                  },
            )
          }
        >
          <Plus size={16} />
          Add class
        </button>
      </div>

      {formFor("level", "create", "")}

      {levels.length === 0 && (
        <div className="empty">
          <p style={{ margin: 0 }}>
            No classes yet. Add one, then give it subjects, books and chapters.
          </p>
        </div>
      )}

      {levels.map((level) => (
        <section className="panel" key={level.id} aria-labelledby={`lvl-${level.id}`}>
          <div className="tax-node">
            <span className="tax-name">
              <b id={`lvl-${level.id}`}>{level.nameEn}</b>
              <small className="muted">
                {level.nameBn} · {level.id} · {level.subjects.length} subjects
              </small>
            </span>
            {rowActions(
              "level",
              level.id,
              level.nameEn,
              { nameEn: level.nameEn, nameBn: level.nameBn, position: level.sort },
              { kind: "subject", nextPosition: level.subjects.length },
            )}
          </div>
          {formFor("level", "update", level.id)}
          {formFor("subject", "create", level.id)}

          <ul className="tax-kids">
            {level.subjects.map((subject) => (
              <li key={subject.id}>
                <div className="tax-node">
                  <button
                    type="button"
                    className="icon-btn"
                    aria-expanded={expanded.has(subject.id)}
                    aria-label={`${expanded.has(subject.id) ? "Hide" : "Show"} books in ${subject.nameEn}`}
                    onClick={() => toggle(subject.id)}
                  >
                    {expanded.has(subject.id) ? (
                      <ChevronDown size={16} />
                    ) : (
                      <ChevronRight size={16} />
                    )}
                  </button>
                  <span className="tax-name">
                    {subject.nameEn}
                    <small className="muted">
                      {subject.nameBn} · {subject.id} · {subject.books.length} books
                    </small>
                  </span>
                  {rowActions(
                    "subject",
                    subject.id,
                    subject.nameEn,
                    {
                      nameEn: subject.nameEn,
                      nameBn: subject.nameBn,
                      position: subject.sort,
                    },
                    { kind: "book", nextPosition: subject.books.length },
                  )}
                </div>
                {formFor("subject", "update", subject.id)}
                {formFor("book", "create", subject.id)}

                {expanded.has(subject.id) && (
                  <ul className="tax-kids">
                    {subject.books.map((book) => (
                      <li key={book.id}>
                        <div className="tax-node">
                          <button
                            type="button"
                            className="icon-btn"
                            aria-expanded={expanded.has(book.id)}
                            aria-label={`${expanded.has(book.id) ? "Hide" : "Show"} chapters in ${book.nameEn}`}
                            onClick={() => toggle(book.id)}
                          >
                            {expanded.has(book.id) ? (
                              <ChevronDown size={16} />
                            ) : (
                              <ChevronRight size={16} />
                            )}
                          </button>
                          <span className="tax-name">
                            {book.nameEn}
                            <small className="muted">
                              {book.nameBn} · {book.chapters.length} chapters
                            </small>
                          </span>
                          {rowActions(
                            "book",
                            book.id,
                            book.nameEn,
                            {
                              nameEn: book.nameEn,
                              nameBn: book.nameBn,
                              position: book.sort,
                            },
                            {
                              kind: "chapter",
                              nextPosition: (book.chapters.at(-1)?.number ?? 0) + 1,
                            },
                          )}
                        </div>
                        {formFor("book", "update", book.id)}
                        {formFor("chapter", "create", book.id)}

                        {expanded.has(book.id) && (
                          <ul className="tax-kids">
                            {book.chapters.map((chapter) => (
                              <li key={chapter.id}>
                                <div className="tax-node">
                                  <span className="tax-name">
                                    <span className="tnum">{chapter.number}.</span>{" "}
                                    {chapter.nameEn}
                                    <small className="muted">{chapter.nameBn}</small>
                                  </span>
                                  {rowActions(
                                    "chapter",
                                    String(chapter.id),
                                    chapter.nameEn,
                                    {
                                      nameEn: chapter.nameEn,
                                      nameBn: chapter.nameBn,
                                      position: chapter.number,
                                    },
                                  )}
                                </div>
                                {formFor("chapter", "update", String(chapter.id))}
                              </li>
                            ))}
                            {book.chapters.length === 0 && (
                              <li className="muted" style={{ padding: "8px 0" }}>
                                No chapters yet.
                              </li>
                            )}
                          </ul>
                        )}
                      </li>
                    ))}
                    {subject.books.length === 0 && (
                      <li className="muted" style={{ padding: "8px 0" }}>
                        No books yet.
                      </li>
                    )}
                  </ul>
                )}
              </li>
            ))}
            {level.subjects.length === 0 && (
              <li className="muted" style={{ padding: "8px 0" }}>
                No subjects yet. Students in a batch on this class can't ask
                anything until it has some.
              </li>
            )}
          </ul>
        </section>
      ))}
    </div>
  );
}
