-- Indexes on tables whose drizzle schema is GENERATED by the better-auth CLI
-- (src/db/schema/auth.ts), which must never be hand-edited. They live here as
-- raw SQL instead, so drizzle-kit does not know about them:
--   * `db:generate` ignores them (it diffs against snapshots, not the DB).
--   * `db:push` WILL propose dropping them. Use `db:migrate` for any database
--     that matters.

-- The admin student and solver lists filter by role, newest first.
CREATE INDEX IF NOT EXISTS "idx_user_role_created" ON "user" USING btree ("role", "created_at" DESC);--> statement-breakpoint
-- Deactivating a batch looks up every student enrolled in it.
CREATE INDEX IF NOT EXISTS "idx_student_profiles_batch" ON "student_profiles" USING btree ("batch_id");
